# @package _global_
# Eval config used by practice for ScienceQA (training verifier)
defaults:
  - /agents/practice/anole_vqa_base@agent
  - _self_

exp_id: "scienceqa_practice_eval"

data:
  dataset: "ScienceQA_eval"
  type: "single"

concurrency: 16
pass_k: 1

verify_filename: "vqa_train_reward.py"
verify_func_name: "verify_func"
